### PR TITLE
updated to 1.2.8

### PR DESCRIPTION
**Pull request by vzaliva**
Updated Paco from v1.0 to v1.2.8 (the latest on official page http://plv.mpi-sws.org/paco/ published in April 2016).

Tested to compile with Coq 8.6 and 8.6.1.

### CODE REVIEW

**Comment by ghost** [comment]
That's interesting. I did not know that the upstream version is still being developed. That makes me wonder whether it is right to duplicate the source here (in `coq-contribs`).

Shouldn't we:
- remove `paco` from `coq-contribs`
- update `coq-paco` OPAM packages so that the source code is pulled from `http://plv.mpi-sws.org/paco/`

?

**Comment by vzaliva** [comment]
One problem I see is with versioning. Now coq-paco opam package has version 8.6.0. If we make it to track the original, it should be 1.2.8 which would show up as a downgrade.

**Comment by ghost** [comment]
That's true. That question should be addressed separately.

However, do you agree that it makes sense to remove `paco` from `coq-contribs` rather than duplicate the upstream repository?

**Comment by vzaliva** [comment]
I am not aware of arrangments with authors to include it in contrib in the first place. If they planned to cease control of this package and let Coq team maintain it as a part of contrib that's one thing. Some open source project has their libraries included in bigger projects where they are maintained as separate version distinct from the original one. (lots examples in Unix word)

On the other hand, if Coq contrlb team have no special interest in maintaining this package and it is not critical to Coq ecosystem that by all means the package should be maintained as a separate package based on the original version.

I got the impression that the latter is the case here.

**Comment by ghost** [comment]
> I am not aware of arrangments with authors to include it in contrib in the first place.

@herbelin Do we know why that was done? Are those reasons still valid?

**Comment by ghost** [comment]
@vzaliva I've got confirmation from @herbelin to proceed with removal of `paco` from `coq-contribs` for the reasons I've described above. The first step would be to redirect the existing OPAM packages so that they point upstream. Can you please check [this PR](https://github.com/coq/opam-coq-archive/pull/219)?

**Comment by vzaliva** [comment]
Will do.

**Comment by ghost** [comment]
Thanks. Sorry for the big delay. :-/

**Comment by vzaliva** [comment]
It looks like the decision is to remove it from contrib per https://github.com/coq/opam-coq-archive/pull/219 Thus I am closing this pull request.

**Pull request closed without merging**
